Flowpack/media-ui

Resources/Private/JavaScript/src/components/App.tsx, Resources/Private/JavaScript/src/components/Pagination.tsx, Resources/Private/JavaScript/src/components/SideBarRight/Inspector/PropertyList.tsx, Resources/Private/JavaScript/src/core/MediaUiTheme.tsx, Resources/Private/JavaScript/src/interfaces/MediaUiTheme.ts
The text-overflow with ellipsis always needs a defined width. Therefore we should provide that.
I added the sidebar width as constant and use some variables in the property list to get a defined width.
Fixes: #41
=> BUGFIX: Add width to propertlist for truncation

Classes/GraphQL/Context/AssetSourceContext.php, Classes/GraphQL/Resolver/Type/AssetResolver.php
To be compatible with all php versions for neos 5.2
we need to remove the array type in the class variables.
That just works with php 7.4 and neos 5.2 is 7.2 and newer.
**What I did**
Removed the array type in the two classes.
Just load the site with the installed package, after clearing the cache.
=> BUGFIX: Remove array type in variable

patches/react-image-lightbox+5.1.1.patch
Introduce patch for the lightbox library to prevent moving a large asset outside of the lightbox area.
Resolves: #47
=> BUGFIX: Prevent showing large images outside of lightbox

Resources/Private/JavaScript/BackendModule/src/components/SideBarRight/Inspector/InspectorContainer.tsx
Fixes: https://github.com/Flowpack/media-ui/issues/51
**What I did**
If a certain inspector element is wider than the inspector's width, it would cause overflow and clipping of overflown content on all elements in the inspector.
I've given an explicit width to the grid column and set it to `minmax(0, 1fr)`. The default value for column width is `auto` which is in turn equivalent to `minmax(min-content, max-content)`. And `min-content` is equal from the largest minimum width of either of inspector children. So if a certain element has a fixed width, it makes the inspector grid column to be equal to its width which makes all other properly sized elements to be stretched and overflow as well.
Watch out for this slight clipping here:
=> BUGFIX: prevent inspector overflow

Configuration/Settings.Neos.yaml, Resources/Private/JavaScript/asset-preview/src/components/AssetPreview.tsx, Resources/Private/JavaScript/core/src/provider/MediaUiProvider.tsx, Resources/Private/JavaScript/media-module/src/components/App.tsx, Resources/Private/JavaScript/media-module/src/components/BottomBar/BottomBar.tsx, Resources/Private/JavaScript/media-module/src/components/BottomBar/Pagination/Pagination.tsx, Resources/Private/JavaScript/media-module/src/components/Dialogs/CreateAssetCollectionDialog.tsx, Resources/Private/JavaScript/media-module/src/components/Dialogs/CreateTagDialog.tsx, Resources/Private/JavaScript/media-module/src/components/Dialogs/Dialog.tsx, Resources/Private/JavaScript/media-module/src/components/Dialogs/UploadDialog.tsx, Resources/Private/JavaScript/media-module/src/components/Main/ListView.tsx, Resources/Private/JavaScript/media-selection-screen/src/MediaSelectionScreen.tsx
This PR implements adjustments in order to integrate the new Media UI seamlessly as a secondary editor within the NodeCreationDialog (implemented in https://github.com/neos/neos-ui/pull/2870).
The changes made consist of slight CSS changes as well as some fixes for compatibility issues:
First of all, the MediaUiProvider needed the information that it is being used within the NodeCreationDialog. The condition to determine this however is a little flimsy right now, due to current limitations of the Main UI.
This PR is checking, whether the NodeCreationDialog is open, because we can assume that if `componentDidMount` of
`MediaSelectionScreen` is being called while the dialog is open, the component definitely must be rendered within the dialog, since the dialog is modal and thus prevents all …
=> BUGFIX: Layout changes for creation dialog

Classes/GraphQL/Resolver/Type/AssetResolver.php
**What I did**
If an asset from a remote proxy is not imported, the last modified date is not used and defaults to 1.1.1970, 01:00:00 . With this PR, the last modified date from the remote asset source is used. 
If there is no local asset, the function getLastModified is used to fetch the latest modify date. This function already exists in the AssetProxyInterface so it has to be implemented. I do not understand why the workaround with the localAssetData is used, so perhaps this can be generally replaced with the method from the interface? 
After integrating an asset source with remote assets (like https://github.com/flownative/neos-canto), the modified date does not default to 1.1.1970, 01:00:00. 
Closes #97
=> FEATURE: get lastModified date from remote proxy

Classes/GraphQL/Resolver/Type/QueryResolver.php, Classes/Service/UsageDetailsService.php, Configuration/Settings.yaml
Currently the maximumFileUploadLimit is equal to upload_max_filesize which results in weird numbers for larger max filesizes. This change makes that value configurable with a value of 10 as default.
=> FEATURE: Make maximumFileUploadLimit configurable

Resources/Private/JavaScript/media-module/src/components/Dialogs/CreateTagDialog.tsx
**What I did**
When creating new Tags, the UI allows for empty tags to be created and then throws an error. 
Just like in the UploadDialog I disabled the create button until there is an actual value entered in the CreateTag Dialog. Also, the enter button on the keyboard does not work anymore until the field is not empty anymore.
When creating a new Tag, the 'create' button is disabled and 'enter' does not create  new tag until an actual value is entered into the textfield.
=> Bugfix: Do not allow empty Tags in create-tag Dialog 

Resources/Private/JavaScript/media-module/src/components/Main/ListView.tsx, Resources/Private/JavaScript/media-module/src/components/Main/ListViewItem.tsx
closes #111 
**What I did**
Currently with very long file names, the filename is not fully shown in Listview. This happens even if there is space to show the whole filename. I changed that to show the full filename. 
I changed the fixed width of the label to a minwidth. 
This shows more of the label but with very long labels this creates a horizontal scrollbar. Perhaps changing up the whole table with fixed widths could solve this. 
Long filenames in listview are now fully shown if the window is big enough. 
Old behavior: 
New Behavior:
=> Bugfix: Change Label width

Resources/Private/JavaScript/media-module/src/components/Dialogs/CreateAssetCollectionDialog.tsx
**What I did**
When creating a new collection, the UI allows empty Collection names. 
I disabled the create button until there is an actual value entered in the Dialog. Also, the enter button on the keyboard does not work anymore until the field is not empty anymore.
This is basically like https://github.com/Flowpack/media-ui/pull/107 , just for Collections
When creating a new Collection, the 'create' button is disabled and 'enter' does not create new Collection until an actual value is entered into the textfield.
=> Bugfix: Do not allow empty collection name in create dialog

Resources/Private/JavaScript/media-module/src/components/Main/ListViewItem.tsx
closes #116 
**What I did**
After Uploading a .pptx file the Type-column in the Media UI becomes very long and creates a horizontal scrollbar on smaller screens. 
To make sure the media type does not take up too much space I have added a max-width of 100px. This is somehow generic and seemed like a good width to me where all smaller mime-types like svg, pdf, mp4, png are still fully displayed. To give people the opportunity to still see the full mime-type I added a title-tag that will be visible on hover 
After uploading a file with a long mime-type the Type is cut off after 100px. On hover the title-tag is shown.
=> BUGFIX: Very long media-types create a horizontal scrollbar 

Resources/Private/JavaScript/core/package.json, Resources/Private/JavaScript/core/src/provider/MediaUiProvider.tsx, Resources/Private/JavaScript/core/typings/DateTime.d.ts, Resources/Private/JavaScript/media-module/src/components/Main/ListViewItem.tsx, Resources/Private/JavaScript/media-module/src/components/Main/Thumbnail.tsx, Resources/Private/Translations/en/Main.xlf, yarn.lock
**What I did**
The selection screen now disallows selecting assets not matching the constraints defined in the nodetype yaml definition.
The disallowed assets are also rendered slightly different to make the differentation visible.
Resolves: #14
Use a nodetype property like this to set constraints for asset sources and media types :
```
properties:
image:
ui:
inspector:
editorOptions:
accept: 'image/jpeg,image/gif'
constraints:
mediaTypes:
- 'image/jpeg'
assetSources:
- 'neos'
- 'pexels'
```
This results in a a limited selection for the asset sources and invalid assets are grayed out and unelectable:
=> FEATURE: Support mediatype constriants

Resources/Private/JavaScript/media-module/src/components/Presentation/Column.tsx
This fixes the following overlap issue in the left sidebar for small window heights that also broke an e2e test:
=> BUGFIX: Prevent items in left sidebar from overlapping on small window heights

Resources/Private/JavaScript/media-module/src/components/SideBarLeft/AssetSourceList.tsx, Resources/Private/JavaScript/media-module/src/components/SideBarLeft/Tree/AssetCollectionTree.tsx
solves: #139
**The Problem**
When the clipboard screen is open, it is still possible to select an asset source or an asset collection via the left side bar. But since the clipboard screen remains open, it seems as if nothing happened after the selection.
**The Solution**
I used the `clipboardVisibleState` recoil state from `@media-ui/feature-clipboard` to explicitly close the clipboard screen whenever an asset source or an asset collection gets selected via the left side bar.
=> BUGFIX: Close clipboard screen when an asset source or asset collection gets selected

Resources/Private/JavaScript/core/src/components/MediaApplicationWrapper.tsx, Resources/Private/JavaScript/core/src/provider/Intl.tsx, Resources/Private/JavaScript/core/src/provider/MediaUiProvider.tsx, Resources/Private/JavaScript/core/src/state/applicationContextState.ts, Resources/Private/JavaScript/core/src/state/index.ts, Resources/Private/JavaScript/core/src/state/localStorageEffect.ts, Resources/Private/JavaScript/core/src/state/selectedAssetIdState.ts, Resources/Private/JavaScript/core/src/state/selectedInspectorViewState.ts, Resources/Private/JavaScript/core/typings/global.d.ts, Resources/Private/JavaScript/media-details-screen/src/MediaDetailsScreen.tsx, Resources/Private/JavaScript/media-details-screen/src/components/Details.tsx, Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/AssetInspector.tsx, Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/Tasks.tsx, Resources/Private/JavaScript/media-module/src/components/TopBar/AssetsFilter/AssetTypeFilter.tsx, Resources/Private/JavaScript/media-module/src/index.tsx, Resources/Private/JavaScript/media-selection-screen/src/MediaSelectionScreen.tsx
Separate selection context between application states to make the details and partially the selection view independent of the browser.
The initial state is now applied to the RecoilRoot via the MediaApplicationWrapper which also cleans up the code of the 3 application variants.
=> BUGFIX: Details view shows broken or incorrect inspector

Resources/Private/Translations/en/Main.xlf
English translation file contains duplicate entry for id: action.selectAsset.invalidType.message.
This commit removes one of this entries to have single one.
=> TASK: Remove duplicate entry in the en/Main.xlf translation file

Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/TagSelectBox.tsx
**What I did**
The `TagSelectBox` component was modified to display search box.
I have updated the `MultiSelectBox` component to enable the search option.
Open selected asset properties and use the search box under tags select list to search for tags.
Before:
After:
=> FEATURE: Make the tag select box to work with search field

Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/TagSelectBox.module.css, Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/TagSelectBox.tsx
This commit cleans up a bit `TagSelectBox` component:
- references in names to collections were removed
- dedicated css file was created for `TagSelectBox` this module
- small changes in code
=> [TASK] Cleanup TagSelectBox component

Classes/Service/AssetCollectionService.php
This problem appeared due to variants getting the same collection applied as their original asset in https://github.com/neos/neos-development-collection/pull/3562
Fixes: #224
=> BUGFIX: Don’t include asset variants in counts

Classes/GraphQL/Resolver/Type/MutationResolver.php, Resources/Private/JavaScript/asset-collections/src/components/DeleteButton.tsx, Resources/Private/JavaScript/asset-editing/src/components/EditAssetDialog.tsx, Resources/Private/JavaScript/asset-tags/src/components/CreateTagDialog.tsx, Resources/Private/JavaScript/asset-upload/src/components/FilePreview.module.css, Resources/Private/JavaScript/asset-upload/src/components/FilePreview.tsx, Resources/Private/JavaScript/asset-upload/src/components/PreviewSection.module.css, Resources/Private/JavaScript/asset-upload/src/components/PreviewSection.tsx, Resources/Private/JavaScript/asset-variants/src/components/VariantsInspector.tsx, Resources/Private/JavaScript/core/src/strategy/ApprovalAttainmentStrategy.ts, Resources/Private/JavaScript/media-module/src/components/Main/ListView.tsx, Resources/Private/JavaScript/similar-assets/src/components/SimilarAssetsModal.tsx, Resources/Private/Translations/de/Main.xlf, Resources/Private/Translations/en/Main.xlf
**What I did**
* I brought the German labels in Sync with the English ones
* I added additional labels where they already existed in the TypeScript files, but were not in the XLF
* I added some additional `translate()`, `translateById()` calls where labels were hardcoded
=> TASK: Add translations for labels, finish German translation

Resources/Private/JavaScript/asset-collections/src/components/AssetCollectionTree.tsx, Resources/Private/JavaScript/asset-collections/src/components/AssetCollectionTreeNode.tsx, Resources/Private/JavaScript/asset-collections/src/components/TagTreeNode.tsx, Resources/Private/JavaScript/asset-collections/src/helpers/collectionPath.ts, Resources/Private/JavaScript/asset-collections/src/provider/AssetCollectionTreeDndProvider.tsx, Resources/Private/JavaScript/asset-collections/typings/AssetCollection.ts, Resources/Private/JavaScript/media-details-screen/src/MediaDetailsScreen.tsx, Resources/Private/JavaScript/media-details-screen/src/components/Details.tsx, Resources/Private/JavaScript/media-details-screen/src/components/PreviewActions.tsx, Resources/Private/JavaScript/media-module/src/index.tsx, Resources/Private/JavaScript/media-module/src/lib/FontAwesome.ts, Resources/Private/JavaScript/media-selection-screen/src/MediaSelectionScreen.tsx
With this change drag&drop for collections is possible.
The dragged node will be sorted into its new parent based on the alphabetic sorting and not on the drop position.
Resolves: #190
https://github.com/Flowpack/media-ui/assets/596967/c73a0d87-9819-4e9e-8372-0bfb10f48f6f
=> FEATURE: Enable drag & drop for asset collections

Classes/Aspect/HierarchicalAssetCollectionAspect.php, Classes/Command/AssetCollectionsCommandController.php, Classes/Domain/Model/HierarchicalAssetCollectionInterface.php, Classes/GraphQL/Resolver/Type/MutationResolver.php, Classes/Security/Authorization/Privilege/Doctrine/AssetAssetCollectionConditionGenerator.php, Classes/Security/Authorization/Privilege/Doctrine/AssetConditionGenerator.php, Classes/Security/Authorization/Privilege/Doctrine/HierarchicalAssetCollectionConditionGenerator.php, Classes/Security/Authorization/Privilege/ReadAssetPrivilege.php, Classes/Security/Authorization/Privilege/ReadHierarchicalAssetCollectionPrivilege.php, Classes/Service/AssetCollectionService.php, Classes/Utility/AssetCollectionUtility.php, Migrations/Mysql/Version20240222092731.php, Migrations/Postgresql/Version20240223075804.php, Readme.md, Resources/Private/GraphQL/schema.root.graphql, Resources/Private/JavaScript/asset-collections/src/fragments/assetCollection.ts, Resources/Private/JavaScript/asset-collections/typings/AssetCollection.ts, Tests/Functional/Domain/Model/AssetCollectionTest.php
**What I did**
This change adds a new column to the collection „path“. Which allows a simple privilege check whether a user can access nested collections.
Resolves: #232
Each collection has a new field "path" which is used to store the full hierarchical path of a collection.
This path can be used with the newly added privileges to limit access to collections and contained assets.
Run the following commands to make the feature work
```console
./flow doctrine:migrate
./flow assetcollections:updatepaths
```
And use&adapt the following policy for testing:
```yaml
privilegeTargets:
'Flowpack\Media\Ui\Security\Authorization\Privilege\ReadHierarchicalAssetCollectionPrivilege':
'Some.Package:ReadSpecialAssetCollectionAndSubCollections':
matcher: …
```
=> FEATURE: Implement privilege for hierarchical asset collections

Classes/Service/UsageDetailsService.php
Addresses #234
**What I did**
The usage urls now do not include the port when it is not part of the actual domain.
Changing the server request for generating usage urls from the server globals to the http request of the active request.
It is working in our local, staging and production setups. When deploying to an environment where neos is running in a docker container and the domain does not include the port, then it should work correctly.
=> BUGFIX: Use http request for generating usage urls

Classes/GraphQL/Resolver/Type/QueryResolver.php, Configuration/Policy.yaml, Readme.md, Resources/Private/GraphQL/schema.root.graphql, Resources/Private/JavaScript/asset-collections/src/components/AddAssetCollectionButton.tsx, Resources/Private/JavaScript/asset-collections/src/components/AddTagButton.tsx, Resources/Private/JavaScript/asset-collections/src/components/AssetCollectionTreeNode.tsx, Resources/Private/JavaScript/asset-collections/src/components/DeleteButton.tsx, Resources/Private/JavaScript/core/src/hooks/useConfigQuery.ts, Resources/Private/JavaScript/core/src/queries/config.ts, Resources/Private/JavaScript/dev-server/src/server.ts, Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/AssetCollectionInspector.tsx, Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/ParentCollectionSelectBox.tsx, Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/TagInspector.tsx, Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/TagSelectBoxAssetCollection.tsx
With this change the various buttons, d&d actions and editing of tags and collections can be controlled via privileges.
=> FEATURE: Implement manage tags and collections privileges

Classes/GraphQL/Resolver/Type/AssetCollectionResolver.php, Classes/GraphQL/Resolver/Type/MutationResolver.php, Resources/Private/GraphQL/schema.root.graphql, Resources/Private/JavaScript/asset-collections/src/components/DeleteButton.tsx, Resources/Private/JavaScript/asset-collections/src/fragments/assetCollection.ts, Resources/Private/JavaScript/asset-collections/typings/AssetCollection.ts, Resources/Private/JavaScript/dev-server/src/fixtures/index.ts, Resources/Private/JavaScript/dev-server/src/server.ts, Resources/Private/JavaScript/media-module/package.json, phpstan.neon, yarn.lock
With this change its not possible anymore to delete an asset collection that has assigned assets
or is the default collection of a site.
Resolves #245 
Based on #244
=> FEATURE: Protect referenced asset collections from being deleted

Classes/GraphQL/Resolver/Type/MutationResolver.php, Classes/GraphQL/Resolver/Type/QueryResolver.php, Classes/Service/AssetCollectionService.php, Resources/Private/GraphQL/schema.root.graphql, Resources/Private/JavaScript/core/src/hooks/useConfigQuery.ts, Resources/Private/JavaScript/core/src/queries/config.ts, Resources/Private/JavaScript/dev-server/src/server.ts, Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/CollectionSelectBox.tsx, Resources/Private/JavaScript/media-module/src/components/SideBarRight/Inspector/ParentCollectionSelectBox.tsx
The old media browser auto assigned assets without a collection to the default collection of a site if one is configured. This behaviour has now been duplicated.
Also It's now impossible to remove the last collection of an asset in "folder mode" and when a default collection is configured for the current site.
Resolves: #246 
Based on: #245
=> FEATURE: Auto assign new assets to default collection and prevent removing last collection depending on config

package.json, yarn.lock
This pull request tested if the end-to-end tests run with the release candidate 4 of version 3.7.0. But sadly, it did not work out. So the PR also upgrades testcafe from version 3.5 to 3.6 and uses the Firefox for the GitHub actions.
When 3.7.0 is released we can try https://github.com/DevExpress/testcafe/issues/8286 it again.
=> TASK: Upgrade to testcafe to version 3.6.2

Classes/GraphQL/Resolver/Type/MutationResolver.php, Classes/Transform/FlowErrorTransform.php, Configuration/Settings.GraphQL.yaml, Resources/Private/JavaScript/asset-collections/src/components/CreateAssetCollectionDialog.tsx, Resources/Private/JavaScript/asset-collections/src/components/DeleteButton.tsx, Resources/Private/JavaScript/asset-tags/src/components/CreateTagDialog.tsx, Resources/Private/JavaScript/asset-upload/src/components/Dialogs/NewAssetDialog.tsx, Resources/Private/JavaScript/media-module/src/components/Main/AssetActions.tsx, Resources/Private/JavaScript/media-module/src/core/CreateErrorHandler.ts, Resources/Private/Translations/de/Main.xlf, Resources/Private/Translations/en/Main.xlf
The t3n GraphQL package includes a transformer that bypasses Flow Framework exceptions in GraphQL error handling. The error currently lacks the exception code as part of the information. By including this code (often a timestamp), we can render custom error messages in the backend and support localization.
Relates: #240
=> FEATURE: Use custom transformer for flow exceptions

Resources/Private/JavaScript/asset-collections/src/components/AddTagButton.tsx, Resources/Private/JavaScript/asset-tags/src/components/CreateTagDialog.tsx, Resources/Private/JavaScript/asset-tags/src/state/createTagDialogState.ts, Resources/Private/JavaScript/media-module/tests/tags.ts, Resources/Private/Translations/de/Main.xlf, Resources/Private/Translations/en/Main.xlf
To prevent exceptions and make it more user-friendly this change validated the tag creation form so that you cannot create an empty tag or a tag that already exists.
Related to issue #240
**New behavior:**
https://github.com/user-attachments/assets/7fa10a7b-c2b5-4f1b-babc-165f7969345b
=> FEATURE: Adds validation for create tag dialog

Classes/Domain/Model/AssetSource/NeosAssetProxyRepository.php, Classes/Domain/Model/Dto/MutationResult.php
To get rid of PHP 8.4 deprecation warnings
=> BUGFIX: Explicit marking of nullable parameter

Classes/GraphQL/Resolver/Type/AssetResolver.php
**What I did**
fix that  download always dowloaded the preview png instead of file
#259 
changed $asset to $assetProxy in condition
I found ProvidesOriginalUriInterface is only implemented in NeosAssetProxy so that makes sense
Download of pdf works again for example
=> BUGFIX: Correct asset download url
